Lesson2
brand989/javaScriptFirstLesson pull request #2
Opened 2020-10-13 15:51 UTC by brand989

2020-10-13 19:25 UTC, HaseProgram requested changes

2020-10-13 19:25 UTC, HaseProgram commented on script.js
> +}else{
Старайтесь придерживаться форматирования: не забываем про пробелы.

2020-10-13 19:25 UTC, HaseProgram commented on script.js
> +// По седьмому не до конца понял, проичтал статью но до конца не смог разобраться https://habr.com/ru/company/ruvds/blog/337732/
Хорошая статья, это просто интересные моменты спецификации) Наизусть это все знать разумеется не надо, но полезно знать сами результаты.

2020-10-14 06:57 UTC, brand989 commented on script.js
> +}else{
Спасибо, начал перепроверять пробелы  почти всегда в переменных, а вот про операторы и функции забываю.

2020-10-14 06:58 UTC, brand989 commented on script.js
> +alert(power(5,1));
Увидел уже решение на уроке, но и сам подумал, уже когда сдал, что про 0 забыл, и придумал решение, хотя оно более массивнее, чем Вы показали, но работает.

function power(val, pow) {
    
    if (pow < 1) {
        return 1
    } else if (pow === 1) {
        return val
    } else {
    return val*power(val, pow-1)
    }
}

2020-10-15 05:58 UTC, merged